using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace KindleHub.Client.Games;

/// <summary>
/// Sudoku — 9x9, every row/column/box has 1-9 once. The puzzle is generated by
/// filling a completed grid, blanking cells and confirming the result still has a
/// single solution, so it never ships a puzzle you have to guess through.
/// </summary>
public sealed class SudokuGame : GameBase
{
    public const int Side = 9;
    private static readonly Random Rng = new();

    private readonly List<GameCell> _cells = new();
    private readonly int[] _given = new int[Side * Side];
    private readonly int[] _values = new int[Side * Side];
    private int _filled;

    public SudokuGame()
    {
        for (int i = 0; i < Side * Side; i++) _cells.Add(Blank());
        Reset();
    }

    public override string Slug => "sudoku";
    public override string Name => "Sudoku";
    public override int Columns => Side;
    public override IReadOnlyList<GameCell> Cells => _cells;
    public override int Score => Solved ? 10 : 0;
    public override string? ResultText => Solved ? "Solved — every row, column and box has 1-9." : null;
    public override string StatusText => Solved
        ? "Solved."
        : $"{_filled}/{Side * Side} filled · tap an empty square to cycle 1–9, then blank";

    private bool Solved
    {
        get
        {
            var grid = new int[Side * Side];
            for (int i = 0; i < grid.Length; i++)
                grid[i] = _given[i] != 0 ? _given[i] : _values[i];

            if (grid.Any(v => v == 0)) return false;

            for (int row = 0; row < Side; row++)
            {
                var seen = new bool[Side + 1];
                for (int col = 0; col < Side; col++)
                {
                    int v = grid[row * Side + col];
                    if (v < 1 || v > Side || seen[v]) return false;
                    seen[v] = true;
                }
            }

            for (int col = 0; col < Side; col++)
            {
                var seen = new bool[Side + 1];
                for (int row = 0; row < Side; row++)
                {
                    int v = grid[row * Side + col];
                    if (v < 1 || v > Side || seen[v]) return false;
                    seen[v] = true;
                }
            }

            for (int br = 0; br < Side; br += 3)
                for (int bc = 0; bc < Side; bc += 3)
                {
                    var seen = new bool[Side + 1];
                    for (int y = 0; y < 3; y++)
                        for (int x = 0; x < 3; x++)
                        {
                            int v = grid[(br + y) * Side + bc + x];
                            if (v < 1 || v > Side || seen[v]) return false;
                            seen[v] = true;
                        }
                }

            return true;
        }
    }

    public override void Reset()
    {
        var solution = GenerateSolvedGrid();
        var puzzle = (int[])solution.Clone();

        // Blank ~52 cells, then only keep the puzzle if it still solves uniquely.
        var order = Enumerable.Range(0, Side * Side).OrderBy(_ => Rng.Next()).ToList();
        int removed = 0;
        foreach (var i in order)
        {
            if (removed >= 52) break;
            if (puzzle[i] == 0) continue;
            int keep = puzzle[i];
            puzzle[i] = 0;
            if (CountSolutions(puzzle) == 1) removed++; else puzzle[i] = keep;
        }

        Array.Copy(puzzle, _given, Side * Side);
        Array.Clear(_values, 0, _values.Length);
        _filled = _given.Count(v => v != 0);
        ScoreCounts = false;
        Redraw();
    }

    // ─── generation ──────────────────────────────────────────────────────────
    private static int[] GenerateSolvedGrid()
    {
        var grid = new int[Side * Side];
        Fill(grid, 0);
        return grid;
    }

    private static bool Fill(int[] grid, int pos)
    {
        if (pos == grid.Length) return true;
        int row = pos / Side, col = pos % Side;
        var nums = Enumerable.Range(1, Side).OrderBy(_ => Rng.Next()).ToArray();
        foreach (var n in nums)
        {
            if (!Fits(grid, row, col, n)) continue;
            grid[pos] = n;
            if (Fill(grid, pos + 1)) return true;
            grid[pos] = 0;
        }
        return false;
    }

    private static bool Fits(int[] grid, int row, int col, int n)
    {
        for (int i = 0; i < Side; i++)
        {
            if (grid[row * Side + i] == n) return false;
            if (grid[i * Side + col] == n) return false;
        }
        int br = row / 3 * 3, bc = col / 3 * 3;
        for (int y = 0; y < 3; y++)
            for (int x = 0; x < 3; x++)
                if (grid[(br + y) * Side + bc + x] == n) return false;
        return true;
    }

    /// <summary>Counts solutions, bailing out at 2 — the generator only needs "is it unique?".</summary>
    private static int CountSolutions(int[] puzzle)
    {
        int count = 0;
        var grid = (int[])puzzle.Clone();
        Count(grid, 0, ref count);
        return count;
    }

    private static void Count(int[] grid, int pos, ref int solutions)
    {
        if (solutions > 1) return;
        if (pos == grid.Length) { solutions++; return; }
        if (grid[pos] != 0) { Count(grid, pos + 1, ref solutions); return; }
        int row = pos / Side, col = pos % Side;
        for (int n = 1; n <= Side; n++)
        {
            if (!Fits(grid, row, col, n)) continue;
            grid[pos] = n;
            Count(grid, pos + 1, ref solutions);
            grid[pos] = 0;
            if (solutions > 1) return;
        }
    }

    // ─── input ───────────────────────────────────────────────────────────────
    private int _selected = -1;

    /// <summary>Cycle the selected square through 1-9 and back to blank, no keyboard needed.</summary>
    public override bool OnTap(int index)
    {
        if (index < 0 || index >= _values.Length || _given[index] != 0) return false;
        _selected = index;
        _values[index] = (_values[index] + 1) % 10;
        _filled = _given.Count(v => v != 0) + _values.Count(v => v != 0);
        if (Solved) ScoreCounts = true;
        Redraw();
        return true;
    }

    public override void Redraw()
    {
        for (int i = 0; i < _cells.Count; i++)
        {
            var c = _cells[i];
            bool given = _given[i] != 0;
            int v = given ? _given[i] : _values[i];
            c.Text = v == 0 ? "" : v.ToString();
            c.IsEnabled = !given && !Solved;
            c.FontSize = 20;
            c.Bold = true;
            c.Foreground = given ? Ink : Accent;
            c.Background = i == _selected ? Tiles4[1] : Cell;
            int row = i / Side, col = i % Side;
            c.BorderBrush = Board;
            c.BorderThickness = new Avalonia.Thickness(
                col % 3 == 0 ? 2 : 0.5,
                row % 3 == 0 ? 2 : 0.5,
                col == Side - 1 ? 2 : 0,
                row == Side - 1 ? 2 : 0);
        }
    }

    /// <summary>Exposed for the self-test: a generated puzzle must have exactly one answer.</summary>
    public static int CountSolutionsForTest(int[] puzzle) => CountSolutions(puzzle);
}
