using System;
using System.Collections.Generic;
using System.Linq;

namespace KindleHub.Client.Games;

/// <summary>Lights Out — tap a tile to flip it and its neighbours; clear the board.</summary>
public sealed class LightsOutGame : GameBase
{
    public const int Side = 5;

    private readonly List<GameCell> _cells = new();
    private readonly bool[] _on = new bool[Side * Side];
    private int _moves;

    public LightsOutGame()
    {
        for (int i = 0; i < Side * Side; i++) _cells.Add(Blank());
        Reset();
    }

    public override string Slug => "lightsout";
    public override string Name => "Lights Out";
    public override int Columns => Side;
    public override IReadOnlyList<GameCell> Cells => _cells;
    public override int Score => Solved ? Math.Max(0, 1000 - _moves * 10) : 0;
    public override string? ResultText => Solved ? $"Solved in {_moves} moves." : null;

    public override string StatusText => Solved
        ? $"Solved in {_moves} moves — try for fewer."
        : $"Moves {_moves} · switch every light off";

    private bool Solved => _on.All(b => !b);

    public override void Reset()
    {
        // Every board is generated by making legal presses from the solved state.
        // That guarantees the starting position is reachable, unlike an arbitrary
        // random 5x5 bitmap.
        Array.Clear(_on, 0, _on.Length);
        int presses = 20 + Random.Shared.Next(31);
        for (int i = 0; i < presses; i++)
            Toggle(Random.Shared.Next(_on.Length));

        if (Solved) Toggle(Random.Shared.Next(_on.Length));

        _moves = 0;
        ScoreCounts = false;
        Redraw();
    }

    public override bool OnTap(int index)
    {
        if (index < 0 || index >= _on.Length || Solved) return false;
        int x = index % Side, y = index / Side;
        Toggle(index);
        _moves++;
        if (Solved) ScoreCounts = true;
        Redraw();
        return true;
    }


    private static IEnumerable<int> Indices(int index)
    {
        int x = index % Side, y = index / Side;
        foreach (var (nx, ny) in Neighbours(x, y))
            if (nx >= 0 && ny >= 0 && nx < Side && ny < Side)
                yield return ny * Side + nx;
    }

    private void Toggle(int index)
    {
        foreach (int i in Indices(index)) _on[i] = !_on[i];
    }

    /// <summary>The tapped tile plus its orthogonal neighbours — the classic rule.</summary>
    public static IEnumerable<(int dx, int dy)> Neighbours(int x, int y) => new[]
    {
        (x, y), (x - 1, y), (x + 1, y), (x, y - 1), (x, y + 1),
    };

    public override void Redraw()
    {
        for (int i = 0; i < _cells.Count; i++)
        {
            var c = _cells[i];
            bool on = _on[i];
            c.Text = on ? "●" : "";
            c.Background = on ? Tiles4[4] : Cell;
            c.Foreground = Cell;
            c.IsEnabled = !Solved;
            c.FontSize = 30;
            c.Bold = true;
        }
    }
}
