using System;
using System.Collections.Generic;
using System.Linq;

namespace KindleHub.Client.Games;

/// <summary>
/// Number Slide — slide tiles into 1..N order with a single gap. Every puzzle is
/// generated by walking the gap around a solved board, so it is always solvable.
/// </summary>
public sealed class NumberSlideGame : GameBase
{
    public const int Side = 4;
    public const int Tiles = Side * Side - 1;

    private readonly List<GameCell> _cells = new();
    private readonly int[] _tiles = new int[Tiles + 1]; // last slot is the gap
    private int _gap;
    private int _moves;
    private int _best;
    private bool _solved;
    private readonly List<int> _shuffle = new();

    /// <summary>
    /// The cell indices slid into the gap while shuffling. Playing it backwards
    /// solves the board, which is the proof that every generated puzzle is
    /// solvable; exposed for the self-test.
    /// </summary>
    public IReadOnlyList<int> Shuffle => _shuffle;

    public NumberSlideGame()
    {
        for (int i = 0; i < _tiles.Length; i++) _cells.Add(Blank());
        Reset();
    }

    public override string Slug => "numslide";
    public override string Name => "Number Slide";
    public override int Columns => Side;
    public override IReadOnlyList<GameCell> Cells => _cells;
    public override int Score => _moves;
    public override string? ResultText => _solved ? $"Solved in {_moves} moves." : null;

    public override string StatusText => _solved
        ? $"Solved in {_moves} moves" + (_best > 0 ? $" (your best: {_best})." : ".")
        : $"{_moves} moves · tap a tile next to the gap";

    public override void Reset()
    {
        // Start solved, then shuffle purely by sliding, which is what guarantees
        // the puzzle is reachable — a plain shuffle can be unsolvable.
        for (int i = 0; i < _tiles.Length; i++) _tiles[i] = i < Tiles ? i + 1 : 0;
        _gap = Tiles;

        int steps = 120 + Random.Shared.Next(120);
        _shuffle.Clear();
        for (int s = 0; s < steps; s++)
        {
            var options = Neighbours(_gap);
            // Record where the gap WAS: to undo a move you tap the square the gap
            // came from, not the one the tile came from.
            _shuffle.Add(_gap);
            SlideTo(options[Random.Shared.Next(options.Count)]);
        }

        _moves = 0;
        _solved = false;
        ScoreCounts = false;
        Redraw();
    }

    /// <summary>
    /// The cell indices that share an edge with <paramref name="cell"/>. Linear
    /// ±1 is not enough: that would let a tile slide across a row boundary.
    /// </summary>
    private List<int> Neighbours(int cell)
    {
        var list = new List<int>(4);
        int col = cell % Side, row = cell / Side;
        if (col > 0) list.Add(cell - 1);
        if (col < Side - 1) list.Add(cell + 1);
        if (row > 0) list.Add(cell - Side);
        if (row < Side - 1) list.Add(cell + Side);
        return list;
    }

    private void SlideTo(int target)
    {
        if (target < 0 || target >= _tiles.Length) return;
        (_tiles[_gap], _tiles[target]) = (_tiles[target], _tiles[_gap]);
        _gap = target;
    }

    public override bool OnTap(int index)
    {
        if (_solved || index < 0 || index >= _tiles.Length) return false;
        if (!Neighbours(_gap).Contains(index)) return true;   // only edge-adjacent tiles move

        (_tiles[_gap], _tiles[index]) = (_tiles[index], _tiles[_gap]);
        _gap = index;
        _moves++;

        if (IsSolved())
        {
            _solved = true;
            ScoreCounts = true;
            if (_best == 0 || _moves < _best) _best = _moves;
        }
        Redraw();
        return true;
    }

    private bool IsSolved()
    {
        for (int i = 0; i < Tiles; i++)
            if (_tiles[i] != i + 1) return false;
        return _tiles[Tiles] == 0;
    }

    public override void Redraw()
    {
        for (int i = 0; i < _cells.Count; i++)
        {
            var c = _cells[i];
            int v = _tiles[i];
            bool gap = v == 0;
            c.Text = gap ? "" : v.ToString();
            c.Background = gap ? Board : Tiles4[Math.Clamp((int)Math.Log2(v) - 1, 0, Tiles4.Length - 1)];
            c.Foreground = gap ? Muted : v >= 64 ? Cell : Ink;
            c.IsEnabled = !gap && (i == _gap - 1 || i == _gap + 1);
            c.FontSize = 24;
            c.Bold = true;
        }
    }
}
