using System;
using System.Collections.Generic;

namespace KindleHub.Client.Games;

internal static class WordleWordList
{
    internal static readonly HashSet<string> Words = new(StringComparer.Ordinal)
    {
        "ABOUT","ABOVE","ABUSE","ACTOR","ACUTE","ADMIT","ADOPT","ADULT","AFTER","AGAIN",
        "AGENT","AGREE","AHEAD","ALARM","ALBUM","ALERT","ALIEN","ALIKE","ALIVE","ALLOW",
        "ALONE","ALONG","ALTER","AMONG","ANGER","ANGLE","ANGRY","APART","APPLE","APPLY",
        "ARENA","ARGUE","ARISE","ARRAY","ASIDE","ASSET","AUDIO","ADIEU","AUDIT","AVOID","AWAKE",
        "AWARD","AWARE","BADLY","BAKER","BASES","BASIC","BASIS","BEACH","BEGAN","BEGIN",
        "BEING","BELOW","BENCH","BERRY","BIRTH","BLACK","BLADE","BLAME","BLANK","BLAST",
        "BLIND","BLOCK","BLOOD","BLOOM","BLOWN","BOARD","BOOST","BOOTH","BOUND","BRAIN",
        "BRAND","BRAVE","BREAD","BREAK","BREED","BRICK","BRIDE","BRIEF","BRING","BROAD",
        "BROKE","BROWN","BUILD","BUILT","BUYER","CABIN","CABLE","CARRY","CATCH","CAUSE",
        "CHAIN","CHAIR","CHARM","CHASE","CHEAP","CHECK","CHEER","CHIEF","CHILD","CHINA",
        "CHOSE","CIVIL","CLAIM","CLASS","CLEAN","CLEAR","CLIMB","CLOCK","CLOSE","CLOTH",
        "CLOUD","COACH","COAST","COLOR","COULD","COUNT","COURT","COVER","CRAFT","CRANE",
        "CRASH","CRAZY","CREAM","CRIME","CROSS","CROWD","CROWN","CRUDE","CURVE","DAILY",
        "DAIRY","DANCE","DATED","DEALT","DEATH","DEBUT","DELAY","DEPTH","DOING","DOUBT",
        "DOZEN","DRAFT","DRAMA","DRANK","DRAWN","DREAM","DRESS","DRILL","DRINK","DRIVE",
        "DROVE","EARLY","EARTH","EIGHT","ELBOW","ELDER","ELECT","ELITE","EMPTY","ENEMY",
        "ENJOY","ENTER","ENTRY","EQUAL","ERROR","EVENT","EVERY","EXACT","EXIST","EXTRA",
        "FAITH","FALSE","FANCY","FAULT","FAVOR","FEAST","FENCE","FEWER","FIELD","FIFTH",
        "FIFTY","FIGHT","FINAL","FIRST","FIXED","FLAME","FLASH","FLESH","FLOAT","FLOOR",
        "FLOUR","FLOWN","FLUID","FOCUS","FORCE","FORTH","FORTY","FORUM","FOUND","FRAME",
        "FRANK","FRESH","FRONT","FROST","FRUIT","FULLY","FUNNY","GIANT","GIVEN","GLASS",
        "GLOBE","GLORY","GOING","GRACE","GRADE","GRAND","GRANT","GRAPE","GRAPH","GRASS",
        "GREAT","GREEN","GROSS","GROUP","GROWN","GUARD","GUESS","GUEST","GUIDE","HAPPY",
        "HARSH","HEARD","HEART","HEAVY","HENCE","HOUSE","HUMAN","IDEAL","IMAGE","IMPLY",
        "INDEX","INNER","INPUT","ISSUE","JOINT","JUDGE","JUICE","KNIFE","KNOCK","KNOWN",
        "LABEL","LARGE","LASER","LATER","LAUGH","LAYER","LEARN","LEASE","LEAST","LEAVE",
        "LEGAL","LEVEL","LIGHT","LIMIT","LOCAL","LOGIC","LOOSE","LOWER","LUCKY","MAJOR",
        "MAKER","MARCH","MATCH","MAYBE","MAYOR","MEANT","MEDIA","METAL","MIGHT","MINOR",
        "MINUS","MIXED","MODEL","MONEY","MONTH","MORAL","MOTOR","MOUNT","MOUSE","MOUTH",
        "MOVIE","MUSIC","NEEDS","NEVER","NEWER","NIGHT","NOISE","NORTH","NOTED","NOVEL",
        "NURSE","OCCUR","OCEAN","OFFER","OFTEN","ORDER","OTHER","OUGHT","PAINT","PANEL",
        "PAPER","PARTY","PASTE","PATCH","PAUSE","PEACE","PHONE","PHOTO","PIANO","PIECE",
        "PILOT","PITCH","PLACE","PLAIN","PLANE","PLANT","PLATE","POINT","POUND","POWER",
        "PRESS","PRICE","PRIDE","PRIME","PRINT","PRIOR","PRIZE","PROOF","PROUD","PROVE",
        "QUEEN","QUICK","QUIET","QUITE","RADIO","RAISE","RANGE","RAPID","RARELY","REACH",
        "READY","REALM","REBEL","REFER","RIGHT","RIVER","ROBIN","ROBOT","ROUTE","ROYAL",
        "RURAL","SCALE","SCENE","SCOPE","SCORE","SCREW","SENSE","SERVE","SEVEN","SHADE",
        "SHAKE","SHARE","SHARP","SHEEP","SHEET","SHIFT","SHIRT","SHOCK","SHOOT","SHORT",
        "SHOUT","SHOWN","SIGHT","SINCE","SIXTH","SKILL","SLEEP","SLATE","SMALL","SMART",
        "SMILE","SMOKE","SOLAR","SOLID","SOLVE","SORRY","SOUND","SOUTH","SPACE","SPARE","SPARK",
        "SPEAK","SPEED","SPELL","SPEND","SPIKE","SPINE","SPLIT","SPOKE","SPORT","SPRAY",
        "SQUAD","STACK","STAFF","STAGE","STAKE","STAND","STARK","START","STATE","STEAM",
        "STEEL","STICK","STILL","STONE","STOOD","STORE","STORM","STORY","STRIP","STUCK",
        "STUDY","STYLE","SUGAR","SUITE","SUNNY","SUPER","SWEET","TABLE","TAKEN","TASTE",
        "TEACH","TEARS","THANK","THEIR","THERE","THESE","THICK","THING","THINK","THIRD",
        "THOSE","THREE","THROW","TIGHT","TIRED","TITLE","TODAY","TOKEN","TOTAL","TOUCH",
        "TOUGH","TOWER","TRACE","TRACK","TRADE","TRAIL","TRAIN","TREAT","TREND","TRIAL","TRIBE",
        "TRICK","TRIED","TRIES","TRUCK","TRUST","TRUTH","TWICE","UNDER","UNION","UNITY",
        "UNTIL","UPPER","UPSET","URBAN","USAGE","USUAL","VALID","VALUE","VIDEO","VISIT",
        "VOICE","WASTE","WATCH","WATER","WHOLE","WHOSE","WOMAN","WORLD","WORRY","WORTH",
        "WOULD","WRITE","WRONG","WROTE","YIELD","YOUNG","YOUTH","ZEBRA"
    };
}
